version: '3.8'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Indian_Library
      MYSQL_USER: IndianLibrary
      MYSQL_PASSWORD: Indian#456
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    ports:
      - "9002:9002"
    environment:
      dbUser: IndianLibrary
      dbPassword: Indian#456
      dbName: Indian_Library
      hostAddress: db:3306 
    depends_on:
      - db

volumes:
  dbdata:
